apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  observabilityAddonSpec: {}
  nodeSelector:
    node-role.kubernetes.io/infra: true
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
      tlsSecretName: tls-certs-secret
      tlsSecretMountPath: /etc/minio/certs

