apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: collector
  namespace: openshift-logging
spec:
  managementState: Managed
  collector:
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: ""
      operator: Exists
  serviceAccount:
    name: collector
  outputs:
  # To define Remote LMS
  - name: remote-lms
    type: syslog
    syslog:
      rfc: RFC5424
      url: tls://<lms_hostname>:<port>
    tls:
      ca:
        key: ca-bundle.crt
        secretName: lms-tls
      
  # To define Managed Loki
  - name: default-lokistack
    type: lokiStack
    lokiStack:
      target:
        name: logging-loki
        namespace: openshift-logging
      authentication:
        token:
          from: serviceAccount
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  # To forward to Remote LMS
  - name: lms-logs
    inputRefs:
    - audit
    - application
    - infrastructure
    outputRefs:
    - remote-lms
  
  # To forward to Managed Loki
  - name: default-logstore
    inputRefs:
    - audit
    - application
    - infrastructure
    outputRefs:
    - default-lokistack
